---
apiVersion: controllermanager.config.gardener.cloud/v1alpha1
kind: ControllerManagerConfiguration
gardenClientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
controllers:
  plant:
    syncPeriod: 10s
    concurrentSyncs: 5
  seed:
    concurrentSyncs: 5
    syncPeriod: 30s
  # monitorPeriod: 40s
  # shootMonitorPeriod: 300s
  shootMaintenance:
    concurrentSyncs: 5
  # enableShootControlPlaneRestarter: true
  shootHibernation:
    concurrentSyncs: 5
  shootQuota:
    concurrentSyncs: 5
    syncPeriod: 60m
  project:
    concurrentSyncs: 5
    minimumLifetimeDays: 30
    staleGracePeriodDays: 14
    staleExpirationTimeDays: 90
    staleSyncPeriod: 12h
  event:
    concurrentSyncs: 5
    ttlNonShootEvents: 1h
leaderElection:
  leaderElect: true
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s
  resourceLock: configmaps
logLevel: info
kubernetesLogLevel: 0
server:
  http:
    bindAddress: 0.0.0.0
    port: 2718
  https:
    bindAddress: 0.0.0.0
    port: 2719
    tls:
      serverCertPath: dev/tls/gardener-controller-manager.crt
      serverKeyPath: dev/tls/gardener-controller-manager.key
featureGates:
  CachedRuntimeClients: true
