images:
  gardener-resource-manager: image-repository:image-tag

resources:
  requests:
    cpu: 23m
    memory: 47Mi
  limits:
    cpu: 400m
    memory: 512Mi

replicas: 1

leaderElection: {}
# leaseDuration: 15s
# renewDeadline: 10s
# retryPeriod: 2s

controllers:
#  cacheResyncPeriod: 24h0m0s
  managedResource:
    syncPeriod: 1m0s
    concurrentSyncs: 20
    alwaysUpdate: true
  managedResourceHealth:
    syncPeriod: 1m0s
    concurrentSyncs: 10

podAnnotations: {}
