---
apiVersion: {{ include "deploymentversion" . }}
kind: Deployment
metadata:
  name: gardener-resource-manager
  namespace: {{ .Release.Namespace }}
  labels:
    garden.sapcloud.io/role: controlplane
    app: gardener-resource-manager
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      garden.sapcloud.io/role: controlplane
      app: gardener-resource-manager
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        garden.sapcloud.io/role: controlplane
        app: gardener-resource-manager
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-seed-apiserver: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
    spec:
      serviceAccountName: gardener-resource-manager
      containers:
      - name: gardener-resource-manager
        image: {{ index .Values.images "gardener-resource-manager" }}
        imagePullPolicy: IfNotPresent
        command:
        - /gardener-resource-manager
        - --leader-election=true
        - --leader-election-namespace={{ .Release.Namespace }}
        {{- if .Values.leaderElection.leaseDuration }}
        - --leader-election-lease-duration={{ .Values.leaderElection.leaseDuration }}
        {{- end }}
        {{- if .Values.leaderElection.renewDeadline }}
        - --leader-election-renew-deadline={{ .Values.leaderElection.renewDeadline }}
        {{- end }}
        {{- if .Values.leaderElection.retryPeriod }}
        - --leader-election-retry-period={{ .Values.leaderElection.retryPeriod }}
        {{- end }}
        {{- if .Values.controllers.cacheResyncPeriod }}
        - --cache-resync-period={{ .Values.controllers.cacheResyncPeriod }}
        {{- end }}
        - --sync-period={{ .Values.controllers.managedResource.syncPeriod }}
        - --max-concurrent-workers={{ .Values.controllers.managedResource.concurrentSyncs }}
        - --health-sync-period={{ .Values.controllers.managedResourceHealth.syncPeriod }}
        - --health-max-concurrent-workers={{ .Values.controllers.managedResourceHealth.concurrentSyncs }}
        - --always-update={{ .Values.controllers.managedResource.alwaysUpdate }}
        - --namespace={{ .Release.Namespace }}
        - --target-kubeconfig=/etc/gardener-resource-manager/kubeconfig
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}
        volumeMounts:
        - name: gardener-resource-manager
          mountPath: /etc/gardener-resource-manager
      volumes:
      - name: gardener-resource-manager
        secret:
          secretName: gardener-resource-manager
          defaultMode: 420
